name: documind

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.25"

  backend:
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"

  celery_worker:
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"

  eval_worker:
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"

  celery_beat:
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.25"

  postgres:
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.0"

  redis:
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
