"""add hashed_password to users

Revision ID: 99cb697df279
Revises: 0001
Create Date: 2026-03-26 09:23:40.280224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99cb697df279'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('ix_chat_sessions_kb_id', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_workspace_id', table_name='chat_sessions')
    op.alter_column('document_trees', 'executive_summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_documents_kb_id', table_name='documents')
    op.drop_index('ix_documents_workspace_id', table_name='documents')
    op.alter_column('eval_results', 'faithfulness_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_eval_results_message_id', table_name='eval_results')
    op.alter_column('knowledge_bases', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_knowledge_bases_workspace_id', table_name='knowledge_bases')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_index('ix_users_workspace_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_workspace_id', 'users', ['workspace_id'], unique=False)
    op.drop_column('users', 'hashed_password')
    op.create_index('ix_knowledge_bases_workspace_id', 'knowledge_bases', ['workspace_id'], unique=False)
    op.alter_column('knowledge_bases', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('ix_eval_results_message_id', 'eval_results', ['message_id'], unique=False)
    op.alter_column('eval_results', 'faithfulness_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('ix_documents_workspace_id', 'documents', ['workspace_id'], unique=False)
    op.create_index('ix_documents_kb_id', 'documents', ['kb_id'], unique=False)
    op.alter_column('document_trees', 'executive_summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('ix_chat_sessions_workspace_id', 'chat_sessions', ['workspace_id'], unique=False)
    op.create_index('ix_chat_sessions_kb_id', 'chat_sessions', ['kb_id'], unique=False)
    op.create_index('ix_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###
